# fly.toml app configuration file generated for jaspervault-minibridge on 2025-01-05T16:47:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jaspervault-minibridge'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
